# https://docs.lando.dev/plugins/symfony/config.html

name: nft-marketplace
recipe: symfony
config:
  webroot: ./public
  php: '8.2'
  via: nginx
  cache: memcached
  xdebug: false
  database: postgres
  config:
    php: .lando/php.ini

services:
  appserver:
    scanner: false
    ports:
      - 5173:5173
    run:
      - composer install
    build_as_root:
      - apt-get update -y
      - apt-get install -y libgmp-dev
      - docker-php-ext-install gmp
      - docker-php-ext-enable gmp
      - curl -sL https://deb.nodesource.com/setup_20.x | bash -
      - apt-get install -y nodejs
      - npm install yarn -g
  database:
    portforward: 5432
tooling:
  node:
    service: appserver
  npx:
    service: appserver
  yarn:
    service: appserver
  symfony:
    service: appserver
    description: Shortcut for php bin/console
    cmd: php bin/console
