# https://docs.lando.dev/plugins/symfony/config.html

name: nft-marketplace
recipe: symfony
config:
  webroot: ./webapp/public
  php: '8.2'
  via: nginx
  cache: memcached
  xdebug: false
  database: postgres
  config:
    php: .lando/php.ini

services:
  appserver:
    scanner: false
    ports:
      - 5173:5173
    run:
      - composer install
    build_as_root:
      - apt-get update -y
      - curl -sL https://deb.nodesource.com/setup_20.x | bash -
      - apt-get install -y libgmp-dev librabbitmq-dev nodejs
      - docker-php-ext-install gmp
      - docker-php-ext-enable gmp
      - docker-php-ext-install sockets
      - docker-php-ext-enable sockets
      - printf "\n" | pecl install amqp
      - npm install yarn -g
  database:
    portforward: 5432
  rabbitmq:
    api: 3
    type: lando
    services:
      image: rabbitmq:3.13-management
      command: rabbitmq-server
      volumes:
        - rabbitmq_volume:/var/lib/rabbitmq
      environment:
         RABBITMQ_DEFAULT_USER: user
         RABBITMQ_DEFAULT_PASS: password
    volumes:
      rabbitmq_volume: {}
tooling:
  node:
    service: appserver
  npx:
    service: appserver
  yarn:
    service: appserver
  symfony:
    service: appserver
    description: Shortcut for php bin/console
    cmd: php bin/console
proxy:
  rabbitmq:
    - rabbit.lndo.site:15672
