<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20240420225733 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE nft (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, description TEXT NOT NULL, type VARCHAR(255) NOT NULL, imported_on TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, blockchain_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_D9C7463C98073AE1 ON nft (blockchain_id)');
        $this->addSql('CREATE TABLE nft_account_wallet (nft_id INT NOT NULL, account_wallet_id INT NOT NULL, PRIMARY KEY(nft_id, account_wallet_id))');
        $this->addSql('CREATE INDEX IDX_168D0808E813668D ON nft_account_wallet (nft_id)');
        $this->addSql('CREATE INDEX IDX_168D0808535FF8A8 ON nft_account_wallet (account_wallet_id)');
        $this->addSql('ALTER TABLE nft ADD CONSTRAINT FK_D9C7463C98073AE1 FOREIGN KEY (blockchain_id) REFERENCES blockchain (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE nft_account_wallet ADD CONSTRAINT FK_168D0808E813668D FOREIGN KEY (nft_id) REFERENCES nft (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE nft_account_wallet ADD CONSTRAINT FK_168D0808535FF8A8 FOREIGN KEY (account_wallet_id) REFERENCES account_wallet (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE nft DROP CONSTRAINT FK_D9C7463C98073AE1');
        $this->addSql('ALTER TABLE nft_account_wallet DROP CONSTRAINT FK_168D0808E813668D');
        $this->addSql('ALTER TABLE nft_account_wallet DROP CONSTRAINT FK_168D0808535FF8A8');
        $this->addSql('DROP TABLE nft');
        $this->addSql('DROP TABLE nft_account_wallet');
    }
}
