<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20240421080503 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE "account" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, username VARCHAR(255) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, password VARCHAR(255) DEFAULT NULL, registered_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, is_active BOOLEAN NOT NULL, roles JSON NOT NULL, is_verified BOOLEAN NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE account_session (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, browser VARCHAR(255) NOT NULL, os VARCHAR(255) NOT NULL, token VARCHAR(255) NOT NULL, started_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, last_activity_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, account_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_196FC19C9B6B5FBA ON account_session (account_id)');
        $this->addSql('CREATE TABLE account_wallet (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(255) NOT NULL, address VARCHAR(255) NOT NULL, account_data INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_5B5C5C6C216074C9 ON account_wallet (account_data)');
        $this->addSql('CREATE TABLE blockchain (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, chain_id INT NOT NULL, native_token VARCHAR(255) NOT NULL, icon VARCHAR(255) DEFAULT NULL, type VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE nft (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, description TEXT NOT NULL, type VARCHAR(255) NOT NULL, imported_on TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, blockchain_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_D9C7463C98073AE1 ON nft (blockchain_id)');
        $this->addSql('CREATE TABLE nft_account_wallet (nft_id INT NOT NULL, account_wallet_id INT NOT NULL, PRIMARY KEY(nft_id, account_wallet_id))');
        $this->addSql('CREATE INDEX IDX_168D0808E813668D ON nft_account_wallet (nft_id)');
        $this->addSql('CREATE INDEX IDX_168D0808535FF8A8 ON nft_account_wallet (account_wallet_id)');
        $this->addSql('CREATE TABLE rpc_provider (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, url VARCHAR(255) NOT NULL, headers JSON DEFAULT NULL, blockchain_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_2D5B16D698073AE1 ON rpc_provider (blockchain_id)');
        $this->addSql('ALTER TABLE account_session ADD CONSTRAINT FK_196FC19C9B6B5FBA FOREIGN KEY (account_id) REFERENCES "account" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE account_wallet ADD CONSTRAINT FK_5B5C5C6C216074C9 FOREIGN KEY (account_data) REFERENCES "account" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE nft ADD CONSTRAINT FK_D9C7463C98073AE1 FOREIGN KEY (blockchain_id) REFERENCES blockchain (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE nft_account_wallet ADD CONSTRAINT FK_168D0808E813668D FOREIGN KEY (nft_id) REFERENCES nft (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE nft_account_wallet ADD CONSTRAINT FK_168D0808535FF8A8 FOREIGN KEY (account_wallet_id) REFERENCES account_wallet (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE rpc_provider ADD CONSTRAINT FK_2D5B16D698073AE1 FOREIGN KEY (blockchain_id) REFERENCES blockchain (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE account_session DROP CONSTRAINT FK_196FC19C9B6B5FBA');
        $this->addSql('ALTER TABLE account_wallet DROP CONSTRAINT FK_5B5C5C6C216074C9');
        $this->addSql('ALTER TABLE nft DROP CONSTRAINT FK_D9C7463C98073AE1');
        $this->addSql('ALTER TABLE nft_account_wallet DROP CONSTRAINT FK_168D0808E813668D');
        $this->addSql('ALTER TABLE nft_account_wallet DROP CONSTRAINT FK_168D0808535FF8A8');
        $this->addSql('ALTER TABLE rpc_provider DROP CONSTRAINT FK_2D5B16D698073AE1');
        $this->addSql('DROP TABLE "account"');
        $this->addSql('DROP TABLE account_session');
        $this->addSql('DROP TABLE account_wallet');
        $this->addSql('DROP TABLE blockchain');
        $this->addSql('DROP TABLE nft');
        $this->addSql('DROP TABLE nft_account_wallet');
        $this->addSql('DROP TABLE rpc_provider');
    }
}
