<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20240424212116 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE nft_import_queue (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, metadata_uri VARCHAR(255) NOT NULL, inserted_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, imported_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, nft_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A1F869B0E813668D ON nft_import_queue (nft_id)');
        $this->addSql('ALTER TABLE nft_import_queue ADD CONSTRAINT FK_A1F869B0E813668D FOREIGN KEY (nft_id) REFERENCES nft (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE nft ADD address VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE nft ADD token_id VARCHAR(255) NOT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE nft_import_queue DROP CONSTRAINT FK_A1F869B0E813668D');
        $this->addSql('DROP TABLE nft_import_queue');
        $this->addSql('ALTER TABLE nft DROP address');
        $this->addSql('ALTER TABLE nft DROP token_id');
    }
}
